[sel system_yes_no top]
[s]Yes[e]
[s]No[e]

[msg system_camp_card_drop]
[s][f 0 6 255 255]> Are you sure you want to dismiss[n]this Persona?[n][e]

[msg system_camp_card_drop_ng]
[s][f 0 6 255 255]> You can't dismiss a Persona that's[n]currently equipped.[w][e]

[msg system_camp_card_set]
[s][f 0 6 255 255]> Equip this Persona?[n][e]

[msg system_camp_config_title]
[s][f 0 6 255 255]> Return to the title screen?[n][e]

[msg system_camp_quest_offer]
[s]> Accepted Quest [f 2 4 1]:[n]"[clr 1][f 2 4 0][clr 0]"[n][w][e]

[msg system_camp_quest_end]
[s]> Completed Quest [f 2 4 1]:[n]"[clr 1][f 2 4 0][clr 0]"[n][w][e]

[msg system_camp_quest_first]
[s]Quests that you've accepted can be[n]confirmed on the Menu Screen.[n][w][e]

[msg system_camp_skillcard_al]
[s]> [clr 1][f 2 4 0][clr 0] has already[n]been learned.[n][w][e]

[msg system_camp_skillcard_ch]
[s][f 0 6 255 255]> Learn [clr 1][f 2 4 0][clr 0]?[n][e]

[msg system_camp_skillcard_en]
[s]> [clr 1][f 2 4 1][clr 0] learned [clr 1][f 2 4 0][clr 0]![n][w][e]

[msg system_camp_skillcard_dr]
[s]> This Persona cannot remember any[n]more skills. Please choose one to[n]forget.[n][w][e]

[msg system_camp_skillcard_dr_2]
[s][f 0 6 255 255]> Forget [clr 1][f 2 4 0][clr 0]?[n][e]

[msg system_camp_skillcard_ch_2]
[s]> [clr 1][f 2 4 0][clr 0] has learned [clr 1][f 2 4 1][clr 0].[n][w][e]

[msg system_camp_skillcard_fo]
[s]> [clr 1][f 2 4 0][clr 0] has forgotten [clr 1][f 2 4 1][clr 0].[n][w][e]

[msg system_camp_equip_change]
[s]> This Persona is already equipped.[n][w][e]

[msg system_camp_equip_change_2]
[s]> This party member is in battle and[n]cannot follow orders...[n][w][e]

[msg system_camp_item_exe_ng]
[s]> This party member is too far away[n]to use items on...[n][w][e]

[msg system_camp_skill_exe_ng]
[s]> This party member is too far away[n]to hear your orders...[n][w][e]

[msg system_camp_skill_exe_ng_2]
[s]> This party member is in battle and[n]cannot follow orders...[n][w][e]

[msg system_config_cancel]
[s]> Exiting without changing settings.[n]Continue?[n][e]

[msg system_config_item_reset]
[s]> Revert [f 2 4 0] to default settings?[n][e]

[msg system_config_keyconfig_]
[s]> This command has already been assigned.[n]Do you want to overwrite this setting?[n][e]

[msg system_config_confirm]
[s]> Settings have been changed.[n][w][e]

[msg system_config_not_set]
[s]> There are settings that haven't been set.[n][w][e]

[msg system_config_tab_change]
[s]> Returning without changing settings. [n]Will you proceed?[n][e]

[msg system_config_key_assign]
[s]> Press the key you will like to set to.[n]Pressing Esc will return you to the Settings Menu.[n] [n]* Assignable keys are as follows:[n]   Alphanumeric keys, Tab, Caps Lock, Space[n]   Bar, Ctrl, Alt, & Backspace[n][e]

[msg system_config_pad_assign]
[s]> Press the key you will like to set to.[n]Pressing Esc will return you to the Settings Menu.[n][e]

[msg system_config_space_chan]
[s]> There are settings that haven't been set. [n]Changes will not be applied. Will you proceed?[n][e]

[msg system_camp_config_exit]
[s]> Ending the game. Will you proceed?[n][e]

[msg system_config_pad_assign_2]
[s]> Press the button you will like to set to.[n]Pressing the left stick button will [n]return you to the Settings Menu.[n][e]

